### ISSUE TITLE
yt-dlp-silent.exe not compatible with Windows XP

### ISSUE THREAD

**Issue by AstroSkipper** [FalloNero/yt-dlp4vlc#2]
Thanks for your update! Although the **VLC Media Player** is still compatible with **Windows XP** (in version **3.0.20** and **3.0.21 nightly**), your recently created **yt-dlp-silent.exe** file is unfortunately **not**. Can you please fix that? I think you only need to change the compiler for generating executables running on older OSes, too.

**Comment by FalloNero** [comment]
Woopsie yeah I've compiled as a 64bit app with all the new things in vs2022, I'll fix it asap :D

**Comment by FalloNero** [comment]
I've pushed the new compiled version give it a try, i dont really have an xp vm right now :D

**Comment by AstroSkipper** [comment]
> I've pushed the new compiled version give it a try, i dont really have an xp vm right now :D

I tried to open the new compiled **yt-dlp-silent.exe** but again the message "**yt-dlp-silent.exe is not a valid Win32 application**". Sorry for the bad news! As far as I know, the last XP-compatible VS version is **Visual Studio 2019** version **16.7**. This version or an older one should actually be able to generate XP-compatible executables. And here is an additional link to **Stack Overflow**: [https://stackoverflow.com/questions/70263892/how-to-compile-c-app-for-windows-xp-in-msvs](url)

**Comment by AstroSkipper** [comment]
The yt-dlp-silent.exe is still not working under Windows XP for 8 months. Did you give up in the meanwhile on this project?

**Comment by FalloNero** [comment]
i cooked up one in VS2005 should be finally compatible in winxp, let me know :)

**Comment by AstroSkipper** [comment]
I tested your ytdlp-silent-xp.exe file with my modified script and with yours. It unfortunately still doesn't work under Windows XP. However, without an error message this time.

**Comment by FalloNero** [comment]
Does it run? or just plain refuses/crashes or gives some .net dependencies (even tho is c++)?
u can try it by brutally run it with something like ytdlp-silent-xp.exe -s "yt-dlp.exe youtubelink"
make sure ytdlp and ytdlp-silent-xp are in the same dir to avoid path issues

**Comment by AstroSkipper** [comment]
I tried the following command **ytdlp-silent-xp.exe -s "yt-dlp.exe https://www.youtube.com/watch?v=GvfNKNu1yoA"** and got this error message: 

<img width="878" height="146" alt="Image" src="https://github.com/user-attachments/assets/c2aa1072-381d-4e89-8107-6042256ef849" />

Translated: 
Access denied to target file ytdlp-silent-xp.exe!

"This application could not be started because the application configuration is not correct. To resolve the problem, you should reinstall the application."

**Comment by FalloNero** [comment]
Ive rebuilt it in a WinXP SP3 x86 VM using VS2005, it seems to be fully working there, let me know how it goes, mind you it will start a process and never kill it, this shouldnt be an issue with ytdlp as it automatically quits even if it errors out, I'll be adding some logging into a txt if needed to help debugging in case the program doesnt start ytdlp succesfully, for now there is some console debug if ran of a CMD terminal

**Comment by AstroSkipper** [comment]
> I tried the following command **ytdlp-silent-xp.exe -s "yt-dlp.exe https://www.youtube.com/watch?v=GvfNKNu1yoA"** and got this error message:
> 
> Translated: Access denied to target file ytdlp-silent-xp.exe!
> 
> "This application could not be started because the application configuration is not correct. To resolve the problem, you should reinstall the application."

I performed the same command with your recent version of **ytdlp-silent-xp.exe** file, unfortunately without any success. I got again the error message as before.

**Comment by AstroSkipper** [comment]
Since your **ytdlp-silent-xp.exe** file for starting **yt-dlp** hidden is still not working, I modified the code again and cleaned up all unnecessary lines of code inside my **LUA** script mod. From now on, my **PowerShell** command "**PowerShell.exe -windowstyle hidden cmd /c &**" will be executed in the case the **hidecon.exe** file doesn't exist. If, however, the **hidecon.exe** file is present in the main folder of **VLC**, my reduced **hidecon** command "**hidecon &**" will be used instead to start **yt-dlp** hidden. You can find it here: [https://msfn.org/board/topic/185971-youtube-under-windows-xp-downloaders-players-and-browser-support/page/10/#findComment-1284423](url)

**Comment by FalloNero** [comment]
well it has been that way for long, if ytdlp-silent-xp.exe isnt found the powershell gets called by default, on my winxp machine its working. I cant get VLC to call the script but calling it via cmd does indeed wrap the program and does its things, im fixing a few things where it doesnt give back the data in the console to the parent program that called it tho

**Comment by FalloNero** [comment]
This is ytdlp-silent-xp.exe running in WinXP SP3 x86

<img width="565" height="115" alt="Image" src="https://github.com/user-attachments/assets/12317a1d-89a7-4e40-831a-4e93e7455ed8" />

<img width="981" height="398" alt="Image" src="https://github.com/user-attachments/assets/7f668681-6b58-430c-8533-ef9c7a3dcf5d" />

<img width="336" height="410" alt="Image" src="https://github.com/user-attachments/assets/062d8b4f-cc02-4332-a707-cdc334b1f59a" />

The content of yt-dlp-output.txt gives a working url to a m3u8 playlist

https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1767478524/ei/nEBZaZaAG-P2xN8PzYbwuAo/ip/212.237.12.87/id/7e299f1212fe591a/itag/301/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/sgoap/clen%3D26532306%3Bdur%3D1639.375%3Bgir%3Dyes%3Bitag%3D140%3Blmt%3D1767378308287361/sgovp/clen%3D839458947%3Bdur%3D1639.316%3Bgir%3Dyes%3Bitag%3D299%3Blmt%3D1767378352844619/rqh/1/hls_chunk_host/rr2---sn-8npmpu-8jxl.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/cps/329/met/1767456924,/mh/PV/mm/31,29/mn/sn-8npmpu-8jxl,sn-hpa7zn66/ms/au,rdu/mv/m/mvi/2/pl/20/rms/au,au/initcwndbps/991250/bui/AYUSA3As31SffujHqCbeO8T0jCMOMsaGerdVEUO8_yeUBkJe9Ay4u_QJu67-dTvHVreHdk6Z7qn2AZ4F/spc/wH4Qq6PrsZEWg5xn35ARhsvi1D8blVqRWTvLww6kQPYNxvrm4sxVZsJO7OcQfzwZs7KWW_ysx9vqK69KfKXdigzW/vprv/1/ns/DrHflfq7Fju2RcnCKxxgkCAR/playlist_type/CLEAN/dover/11/txp/3309224/mt/1767456339/fvip/1/keepalive/yes/fexp/51355912,51552689,51565116,51565682,51580968/n/eNFAQ0J3V3ML7r8hHG/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,sgoap,sgovp,rqh,xpc,bui,spc,vprv,ns,playlist_type/sig/AJfQdSswRgIhALAVPSn7jcsDxD6inQDfiJ5eVAudV8-fwazyzpRHxuNOAiEAlowsWBb4mWky9dEPqf6AELD8FXdUyTVn-y1yjNJTHV4%3D/lsparams/hls_chunk_host,cps,met,mh,mm,mn,ms,mv,mvi,pl,rms,initcwndbps/lsig/APaTxxMwRQIhAK4sxfWkxKs4pb-WS5nlOOnEsL3qTkhHlwOeNJLPqcHlAiBYVkYIzLJbJGNfS_Ka7g6cXcPKefYA6QWPaLNZh0Xg6Q%3D%3D/playlist/index.m3u8

I'm unable to setup VLC in winXP to run my youtube.lua script but I can confirm that the same exact code used in VS2005/WinXP also compiled in VS2005/Win11 and extracts the url the same way and VLC loads it up properly.
I can only test the url extraction in WinXP but that as seen above works. Its janky at best as its outputting the url into a text file that then the LUA script reads and deletes.

Ill upload the latest exe compiled in WinXP and its vs2005 project and mark this as resolved.

Feel free to edit and modify the script as you wish/prefer for your use case :)

**Comment by AstroSkipper** [comment]
FYI, even the last build of ytdlp-silent-xp.exe doesn't work under Windows XP. Always the same error message I already posted above.
